### ISSUE TITLE
kanban html macro in portal

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jumpscale_portal8#121]
- select right opensource kanban library (there are 3-4 of them)
- create a html macro in jsportal which converts yaml text format to kanban (as embedded in page)
- document this well in jsportal

markdown format as input for macro

```yaml 
-  name: this is story 1
    description: '
       this is description
       multiline
       '
    priority: critical
    state: question 
-  name: story 2
   description: another description
   priority: normal
   state: done
```

requirements
- multiple kanban per page
